syntax = "proto3";

package maptool;

option java_multiple_files = true;
option java_package = "net.rptools.maptool.server.proto.components";
option java_outer_classname = "ComponentProtos";

import "google/protobuf/wrappers.proto";

/*
 * For easier differentiation between protobuf classes and "normal" classes
 * protobuf classes end with "Dto" or "Msg".
 */

message ParentReferenceDto {
  bytes parent_local_id = 1;
}

message PlacementDto {
  double x = 1;
  double y = 2;
  double rotation = 3;
  double scale = 4;
}